### ISSUE TITLE
Usage of generated constants within store modules

### ISSUE THREAD

**Issue by mcquiggd** [cycloidio/vuex-type-const-generator#6]
Firstly, thanks for this project.

I looked at this today, and I have successfully generated a list of constants for getters, mutations, actions, as below (adjusted for brevity):

```
// DO NOT MODIFY THIS FILE: AUTOGENERATED BY vuextcg
export const getters = {
  // Namespaced
  USER_USER: 'user/user'
}

export const mutations = {
  // Namespaced
  USER_SET_USER: 'user/setUser'
}

export const actions = {
  // Namespaced
  USER_AUTO_SIGN_IN: 'user/autoSignIn',
  USER_LOGOUT: 'user/logout',
  USER_SIGN_USER_IN: 'user/signUserIn',
  USER_SIGN_USER_UP: 'user/signUserUp'
}
```

This all works well when using the constants in a Vue file, for example:

```
  import { mapGetters } from 'vuex'
  import { getters } from './store/types.js'
  export default {
    computed: {
      ...mapGetters({ user: getters.USER_USER })
```

However, it seems that when trying to use the generated constants in the Vuex store, within an action in namespaced modules (e.g. to commit a mutation, specifying the name of the mutation by using a constant) it is necessary to also include { root : true} as an argument in the call, for it to resolve the correct mutation.

This is required even in the same module.

```
    logout({ commit }) {
      firebase.auth().signOut()
      commit(mutations.USER_SET_USER, null, { root: true })
    }
```

Omitting {root:true} results in this error:

> [vuex] unknown local mutation type: user/setUser, global type: user/user/setUser

**This does make sense due to [this GitHub commit](https://github.com/vuejs/vuex/pull/420), but, is there a more elegant solution that would obviate the need to pass {root: true} in every commit, and still be able to use constants to avoid magic strings?** 

PLEASE NOTE: The namespaced module is located in a separate file, in a subfolder, and defined as follows:

```
// store/modules/user.js
import { mutations } from './../types.js'

export default {
  namespaced: true,

  // initial state
  state: {
    user: null
  },

  // getters
  getters: {
    user(state) {
      return state.user
    }
  },

  // actions
  actions: {
    logout({ commit }) {
      firebase.auth().signOut()
      commit(mutations.USER_SET_USER, null, { root: true })
    }
  }
}
```

**Comment by ifraixedes** [comment]
I understand that main point of this issue is this question

> **This does make sense due to this GitHub commit, but, is there a more elegant solution that would obviate the need to pass {root: true} in every commit, and still be able to use constants to avoid magic strings?**

As far as I know, there isn't if I understand well what the _Vuex docs_ say about https://vuex.vuejs.org/en/modules.html#accessing-global-assets-in-namespaced-modules

**Comment by mcquiggd** [comment]
@ifraixedes 

Yep, I thought so... 

Well, no major problem for adding these within the store. So I will close this.
